version: '3.9'

services:
  dotnet:
    container_name: 'Ada_app'
    image: 'projeto-ada-docker-denize'
    build:
      context: .
      dockerfile: ./Ada_app/Dockerfile
    restart: always
    ports:
     - "5000:80"
    depends_on:
     - "postgres"
    networks:
      - ada_app_image-network
    env_file:
      - config.env

  postgres:
    container_name: 'postgres_ada'
    image: projeto-ada-docker-denize-db
    build:
      context: .
      dockerfile: ./Postgres/Dockerfile
    networks:
      - ada_app_image-network
    volumes:
      - db-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./Postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    env_file:
      - config.env

networks:
  ada_app_image-network:
    driver: bridge

volumes:
  db-data: {}